export enum QueryKey {
  Courses = 'courses',
  Tag = 'tag',
  Category = 'category',
  Lessons = 'lessons',
  TeacherCourse = 'teacher-course',
  GuestCourse = 'guest-course',
  CourseInfo = 'course-info',
  CourseAddition = 'course-addition',
  Video = 'video',
  CourseLessons = 'course-lessons',
  LessonsLearn = 'lessons-learn',
  Question = 'question',
  QuizStart = 'quiz-start',
  Me = 'me',
}
